In [7]:
# Importing neccessary packages
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import scipy.stats as stats
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.metrics import recall_score, accuracy_score, classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import SelectKBest

In [3]:
df=pd.read_csv("Final_Data.csv")
df.head()

,Unnamed: 0,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,0,1,0,1,0,1,0,0,...,0,0,0,0,0,1,2,29.85,2505,0
1,1,1,0,0,0,34,1,0,0,2,...,2,0,0,0,1,0,3,56.95,1466,0
2,2,1,0,0,0,2,1,0,0,2,...,0,0,0,0,0,1,3,53.85,157,1
3,3,1,0,0,0,45,0,1,0,2,...,2,2,0,0,1,0,0,42.30,1400,0
4,4,0,0,0,0,2,1,0,1,0,...,0,0,0,0,0,1,2,70.70,925,1

### Spliting Data into Train and Test

In [4]:
X=df.drop(columns="Churn")
y=df["Churn"]

In [5]:
X.head()

,Unnamed: 0,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,0,0,0,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29.85,2505
1,1,1,0,0,0,34,1,0,0,2,0,2,0,0,0,1,0,3,56.95,1466
2,2,1,0,0,0,2,1,0,0,2,2,0,0,0,0,0,1,3,53.85,157
3,3,1,0,0,0,45,0,1,0,2,0,2,2,0,0,1,0,0,42.30,1400
4,4,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,925

### Feature Selection

selected 10 feature which has higher correlation.

In [8]:
selection=SelectKBest() # k=10 bydefault
X=selection.fit_transform(X,y)

In [9]:
# this will show feature are taken denote as true other are removed like false
selection.get_support()

array([False, False,  True, False,  True,  True, False, False, False,
        True,  True,  True,  True, False, False,  True,  True, False,
        True, False])

INSIGHTS:- 

According to the features selection, we select the 10 outoff 21 features these are 10 feature selected [Dependents,tenure,Online,Sequrity,OnlineBackup,DeviceProtection,TecSupport,Contract,PapperlessBilling,MonthlyCharges,TotalCharges]

In [10]:
# spliting for train & test
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2)

In [11]:
X_train.shape

(5634, 10)

In [12]:
X.shape

(7043, 10)

In [14]:
y.value_counts()

Churn
0    5174
1    1869
Name: count, dtype: int64

### Applying Into Machine Learning Algorithm

In [16]:
Log_reg = LogisticRegression(C=150, max_iter=150)
Log_reg.fit(X_train, y_train)
log_pred = Log_reg.predict(X_test)

print(f'Accuracy score : {accuracy_score(log_pred, y_test)}')
print(f'Confusion matrix :\n {confusion_matrix(log_pred, y_test)}')
print(f'Classification report :\n {classification_report(log_pred, y_test)}')

Accuracy score : 0.8026969481902059
Confusion matrix :
 [[942 175]
 [103 189]]
Classification report :
               precision    recall  f1-score   support

           0       0.90      0.84      0.87      1117
           1       0.52      0.65      0.58       292

    accuracy                           0.80      1409
   macro avg       0.71      0.75      0.72      1409
weighted avg       0.82      0.80      0.81      1409

INSIGHTS:-

Good Performance – With 80% accuracy, the model is performing well and making correct predictions in most cases.